### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by sudheesh-k** [trondkr/model2roms#21]
Hi,
While compiling I am getting the following error. How can I solve it? 
Thanks in advance for the support.

With regards
sudheesh

----------------------------------------------------
Traceback (most recent call last):
  File "/home/model/miniforge3/envs/model2roms/bin/f2py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 781, in main
    run_compile()
    ~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 753, in run_compile
    builder.compile()
    ~~~~~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 192, in compile
    self.run_meson(self.build_dir)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 187, in run_meson
    self._run_subprocess_command(compile_command, build_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 181, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/model/miniforge3/envs/model2roms/bin/f2py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 781, in main
    run_compile()
    ~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 753, in run_compile
    builder.compile()
    ~~~~~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 192, in compile
    self.run_meson(self.build_dir)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 187, in run_meson
    self._run_subprocess_command(compile_command, build_dir)
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 181, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/model/miniforge3/envs/model2roms/bin/f2py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 781, in main
    run_compile()
    ~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/f2py2e.py", line 753, in run_compile
    builder.compile()
    ~~~~~~~~~~~~~~~^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 192, in compile
    self.run_meson(self.build_dir)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 187, in run_meson
    self._run_subprocess_command(compile_command, build_dir)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/site-packages/numpy/f2py/_backends/_meson.py", line 181, in _run_subprocess_command
    subprocess.run(command, cwd=cwd, check=True)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/model/miniforge3/envs/model2roms/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['meson', 'compile', '-C', 'bbdir']' returned non-zero exit status 1.

**Comment by lfelipefm** [comment]
This problems will be solved with:

conda install -c conda-forge meson

**Comment by sudheesh-k** [comment]
Thanks
